### ISSUE TITLE
pubber fails testing/test_aux.sh

### ISSUE THREAD

**Issue by ewRedstone** [faucetsdn/daq#158]
Exception in thread "main" java.lang.RuntimeException: While reading configuration file /root/local/pubber.json
        at daq.pubber.Pubber.<init>(Pubber.java:73)
        at daq.pubber.Pubber.main(Pubber.java:61)
Caused by: java.io.FileNotFoundException: local/pubber.json (No such file or directory)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:195)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at com.fasterxml.jackson.core.JsonFactory.createParser(JsonFactory.java:773)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2890)
        at daq.pubber.Pubber.<init>(Pubber.java:71)
        ... 1 more
2: faux-eth0@if74: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 3c:5a:b4:1e:8f:0a brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 10.20.70.106/8 brd 10.255.255.255 scope global faux-eth0
       valid_lft forever preferred_lft forever
1d0

**Comment by ewRedstone** [comment]
This is impacting integration testing, we need clear defined instructions and examples on how to make this work in Travis

**Comment by InBrewJ** [comment]
Dealt with in https://github.com/arupiot/daq/pull/8

(please note that the merging of this PR will not _fix_ the problem - it can only be fixed by configuration external to DAQ, which I'll go through tomorrow @ewRedstone)

**Comment by pisuke** [comment]
Closing this issue, UDMI has now been moved to a different repo and this issue is no longer relevant.
