### ISSUE TITLE
gcp_cred triggers need for cloud_iot_config.json

### ISSUE THREAD

**Issue by pisuke** [faucetsdn/daq#309]
@grafnu not sure if this is a feature or a bug.

Just pulled fresh code from master and configured with the following:

```
root@daquntu:~/Code/daq# cat local/system.conf 
# DAQ configuration for the Allied Telesis x230 switch

source misc/system.conf
site_description="Allied Telesis x230"

ext_dpid=0x42
ext_ctrl=enx645aedf40df6
ext_intf=enxb49cdff3015b
ext_ofpt=6653
ext_ofip=192.168.1.10/24
ext_addr=192.168.1.1
sec_port=15

gcp_cred=local/arup-bos-728dcacd3ccf.json

host_tests=misc/all_tests.conf
```

DAQ aborts asking for `local/site/cloud_iot_config.json`.
DAQ CLI log below.

```
root@daquntu:~/Code/daq# cmd/run
Activating venv
Loading config from local/system.conf into inst/config/system.conf
Starting Thu 19 Mar 22:49:05 GMT 2020
Clearing previous state...
Installing local/arup-bos-728dcacd3ccf.json into inst/config...
Activating venv
Loading config from local/system.conf into inst/config/system.conf
Release version 1.0.1
ovsdb-server is running with pid 397
ovs-vswitchd is running with pid 541
Creating mudacl templates...
> Task :compileJava UP-TO-DATE
> Task :processResources NO-SOURCE
> Task :classes UP-TO-DATE
> Task :shadowJar UP-TO-DATE

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 764ms
2 actionable tasks: 2 up-to-date
Running mudacl regression test...
Writing output files to /home/francesco/Code/daq/mudacl/out/acl_templates
Writing output files to /home/francesco/Code/daq/mudacl/out/port_acls
Compare out/acl_templates/ with setup/acl_templates/...
Compare out/port_acls/ with setup/port_acls/...
Activating venv
Loading config from local/system.conf into inst/config/system.conf
> Task :compileJava UP-TO-DATE
> Task :processResources NO-SOURCE
> Task :classes UP-TO-DATE
> Task :shadowJar UP-TO-DATE

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 656ms
2 actionable tasks: 2 up-to-date

Executing mudacl generator on mud_files/...
Writing output files to /home/francesco/Code/daq/inst/acl_templates
inst/acl_templates:
total 40
-rw-r--r-- 1 root root  540 Mar 19 22:49 template_bacnet_acl.yaml
-rw-r--r-- 1 root root  332 Mar 19 22:49 template_bacnet_frdev_acl.yaml
-rw-r--r-- 1 root root  332 Mar 19 22:49 template_bacnet_todev_acl.yaml
-rw-r--r-- 1 root root  768 Mar 19 22:49 template_baseline_acl.yaml
-rw-r--r-- 1 root root 1966 Mar 19 22:49 template_commissioning_acl.yaml
-rw-r--r-- 1 root root 1452 Mar 19 22:49 template_controller_acl.yaml
-rw-r--r-- 1 root root   78 Mar 19 22:49 template_default_acl.yaml
-rw-r--r-- 1 root root 1442 Mar 19 22:49 template_lightbulb_acl.yaml
-rw-r--r-- 1 root root  258 Mar 19 22:49 template_raw_acl.yaml
-rw-r--r-- 1 root root  496 Mar 19 22:49 template_telnet_acl.yaml

inst/port_acls:
total 0
DAQ autostart bin/physical_sec
Activating venv
Loading config from local/system.conf into inst/config/system.conf
Cleaning switch bridge, if any...
Configuring control interface enx645aedf40df6 at 192.168.1.10/24
Checking external connection to 192.168.1.1
PING 192.168.1.1 (192.168.1.1) 56(84) bytes of data.
64 bytes from 192.168.1.1: icmp_seq=1 ttl=64 time=20.5 ms
64 bytes from 192.168.1.1: icmp_seq=2 ttl=64 time=1.84 ms

--- 192.168.1.1 ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1002ms
rtt min/avg/max/mdev = 1.840/11.186/20.532/9.346 ms

DAQ autoclean ip link set down dev enx645aedf40df6
Done with physical switch configuration.
Entering virtual python environment...
Using python3 at /home/francesco/Code/daq/venv/bin/python3
Executing: python3 -u daq/daq.py /home/francesco/Code/daq/local/system.conf
Prepending /home/francesco/Code/daq/binhack to PATH
processing arg: /home/francesco/Code/daq/local/system.conf
Reading config from /home/francesco/Code/daq/local/system.conf
Reading config from misc/system.conf
base_conf=misc/module_config.json
dhcp_lease_time=500s
ext_addr=192.168.1.1
ext_ctrl=enx645aedf40df6
ext_dpid=0x42
ext_intf=enxb49cdff3015b
ext_ofip=192.168.1.10/24
ext_ofpt=6653
gcp_cred=local/arup-bos-728dcacd3ccf.json
host_tests=misc/all_tests.conf
initial_dhcp_lease_time=120s
long_dhcp_response_sec=80
run_mode=local
sec_port=15
site_description="Allied Telesis x230"
site_path=local/site/
INFO:daq:pid is 24124
INFO:gcp:Loading gcp credentials from local/arup-bos-728dcacd3ccf.json
Traceback (most recent call last):
  File "daq/daq.py", line 97, in <module>
    sys.exit(_execute())
  File "daq/daq.py", line 82, in _execute
    daq_runner = runner.DAQRunner(config)
  File "/home/francesco/Code/daq/daq/runner.py", line 46, in __init__
    self.gcp = gcp.GcpManager(self.config, self._queue_callback)
  File "/home/francesco/Code/daq/daq/gcp.py", line 52, in __init__
    self._site_name = self._get_site_name()
  File "/home/francesco/Code/daq/daq/gcp.py", line 168, in _get_site_name
    with open(os.path.join(site_path, 'cloud_iot_config.json')) as config_file:
FileNotFoundError: [Errno 2] No such file or directory: 'local/site/cloud_iot_config.json'
Cleanup ip link set down dev enx645aedf40df6
Done with run, exit 1
```

**Comment by grafnu** [comment]
Internal bug b/151978630

**Comment by pisuke** [comment]
Cool. Unfortunately I don't have a view of the internal bug tracking at the moment. 
Is it P0 or lower priority? 
I'll keep it here for visibility to the test development team.

**Comment by grafnu** [comment]
The internal bug is for our internal work planning. P0 means something is
on fire, so it's not P0.

**Comment by pisuke** [comment]
OK, good to know. 
It would be nice to get the web app functionality back at some point, but OK to use the console for now.

**Comment by grafnu** [comment]
? What do you mean?  It's working fine for us.

**Comment by pisuke** [comment]
> ? What do you mean? It's working fine for us.

Command line works fine but if I add the `gcp_cred` option ins `system.conf` it complains about the `cloud_iot_config.json` file missing.

**Comment by grafnu** [comment]
Ok -- so it's inconvenient, yes -- but that doesn't mean it doesn't work.
You just need to setup that file.

**Comment by pisuke** [comment]
Indeed, I'll set it up. 
But I won't change the wiki tutorials for now. Let's see how many users complain.

**Comment by grafnu** [comment]
Well, I'm going to fix it before the release goes out.
